In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv("spam.csv")

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [12]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == "spam" else 0)
df.shape

(5572, 3)

In [10]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [11]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(df.Message , df.spam , test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [15]:
X_test.shape

(1115,)

In [16]:
type(X_train)

pandas.core.series.Series

In [21]:
X_train[:2]

1912    Lol grr my mom is taking forever with my presc...
779     Happy New year my dear brother. I really do mi...
Name: Message, dtype: object

In [22]:
y_train[:2]

1912    0
779     0
Name: spam, dtype: int64

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
v = CountVectorizer()

In [26]:
X_train_cv = v.fit_transform(X_train.values)

In [28]:
X_train_cv

<4457x7771 sparse matrix of type '<class 'numpy.int64'>'
	with 59251 stored elements in Compressed Sparse Row format>

In [30]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
X_train_cv.shape

(4457, 7771)

In [35]:
v.get_feature_names_out().shape

(7771,)

In [36]:
X_train_np = X_train_cv.toarray()

In [38]:
np.where(X_train_np[0]!= 0 )

(array([1177, 2954, 3259, 3757, 4121, 4195, 4505, 4570, 4679, 5195, 5410,
        6719, 7141, 7574], dtype=int64),)

In [39]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)


MultinomialNB()

In [40]:
X_test_cv = v.transform(X_test)


In [41]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       963
           1       1.00      0.90      0.95       152

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [42]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [43]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [44]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [46]:
y_pred = clf.predict(X_test)

In [47]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       963
           1       1.00      0.90      0.95       152

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115

